USE Northwind 
GO 
CREATE VIEW DBO.VW_AD_F4CDR 
AS
SELECT 
CDR_ID                     =CONVERT(NUMERIC(10)   , [CDR_ID]),
FILE_POSESSION_CODE        =CONVERT(VARCHAR(10) ,[FILE_POSESSION_CODE]),
CUSTOMER_ID                =CONVERT(VARCHAR(16) ,[CUSTOMER_ID]),
CAMPAIGN_CODE              =CONVERT(VARCHAR(12) ,[CAMPAIGN_CODE]),
JOB_NAME                   =CONVERT(VARCHAR(40) ,[JOB_NAME]),
DIAL_SEQUENCE              =CONVERT(NUMERIC(10)   ,[DIAL_SEQUENCE]),
APPROACH_CODE              =CONVERT(NUMERIC(10)   ,[APPROACH_CODE]),
TSR_ID                     =CONVERT(VARCHAR(10) ,[TSR_ID]),
CONTACT_DATE_TIME          =CONVERT(DATETIME         ,[CONTACT_DATE_TIME]),
PLANNED_RECALL_DATETIME    =CONVERT(DATE         ,[PLANNED_RECALL_DATETIME]),
LOGGED_HOURS               =CONVERT(NUMERIC(10)   ,[LOGGED_HOURS]),
TALK_HOURS                 =CONVERT(NUMERIC(10)   ,[TALK_HOURS]),
WRAP_HOURS                 =CONVERT(NUMERIC(10)   ,[WRAP_HOURS]),
WAIT_HOURS                 =CONVERT(NUMERIC(10)   ,[WAIT_HOURS]),
TM_RESULT_CODE             ='',
TSR_RESULT_CODE            =CONVERT(VARCHAR(50) ,[TSR_RESULT_CODE]),
PRODUCT_TYPE_CODE          =CONVERT(VARCHAR(10) ,[PRODUCT_TYPE_CODE]),
SALES_VALIDATION_CODE      =CONVERT(VARCHAR(50) ,[SALES_VALIDATION_CODE]),
SALES_PROD_PLAN_CODE       =CONVERT(VARCHAR(10) ,[SALES_PROD_PLAN_CODE]),
SALES_OPTION_CODE          =CONVERT(VARCHAR(10) ,[SALES_OPTION_CODE]),
SALES_OPT_FAMILY_RELATION  =CONVERT(VARCHAR(1)  ,[SALES_OPT_FAMILY_RELATION]),
MONTHLY_PREMIUM            =CONVERT(NUMERIC(10)   ,[MONTHLY_PREMIUM]),
INSURED_ID                 =CONVERT(NUMERIC(10)   ,[INSURED_ID]),
INSURED_DOB                =CONVERT(DATE         ,[INSURED_DOB]),
INSURED_GENDER             =CONVERT(NUMERIC(10)   ,[INSURED_GENDER]),
INSURED_OCCUPATION         =CONVERT(NUMERIC(10)   ,[INSURED_OCCUPATION]),
SPOUSE_DOB                 =CONVERT(DATE         ,[SPOUSE_DOB]),
SPOUSE_GENDER              =CONVERT(NUMERIC(10)   ,[SPOUSE_GENDER]),
SUPPORTER_AGE              =CONVERT(INT          ,[SUPPORTER_AGE]),
SUPPORTER_GENDER           =CONVERT(NUMERIC(10)   ,[SUPPORTER_GENDER]),
DM_OPT_OUT_DATE            =CONVERT(DATE         ,[DM_OPT_OUT_DATE]),
OBTM_OPT_OUT_DATE          =CONVERT(DATE         ,[OBTM_OPT_OUT_DATE]),
MOBILE_NUMERIC              =CONVERT(VARCHAR(13) ,[MOBILE_NUMERIC]),
PERSONAL_EMAIL_ADDRESS     =CONVERT(VARCHAR(100),[PERSONAL_EMAIL_ADDRESS]),
EXTRA_INFO_TEXT_1          =CONVERT(VARCHAR(255),[EXTRA_INFO_TEXT_1]),
EXTRA_INFO_TEXT_2          =CONVERT(VARCHAR(255),[EXTRA_INFO_TEXT_2]),
EXTRA_INFO_TEXT_3          =CONVERT(VARCHAR(255),[EXTRA_INFO_TEXT_3]),
EXTRA_INFO_TEXT_4          =CONVERT(VARCHAR(255),[EXTRA_INFO_TEXT_4]),
EXTRA_INFO_TEXT_5          =CONVERT(VARCHAR(255),[EXTRA_INFO_TEXT_5]),
EXTRA_INFO_DATE1           =CONVERT(DATE         ,[EXTRA_INFO_DATE1]),
EXTRA_INFO_DATE2           =CONVERT(DATE         ,[EXTRA_INFO_DATE2]),
EXTRA_INFO_DATE3           =CONVERT(DATE         ,[EXTRA_INFO_DATE3]),
EXTRA_INFO_DATE4           =CONVERT(DATE         ,[EXTRA_INFO_DATE4]),
EXTRA_INFO_DATE5           =CONVERT(DATE         ,[EXTRA_INFO_DATE5]),
EXTRA_INFO_NUM1            =CONVERT(NUMERIC(16,6) ,[EXTRA_INFO_NUM1]),
EXTRA_INFO_NUM2            =CONVERT(NUMERIC(16,6) ,[EXTRA_INFO_NUM2]),
EXTRA_INFO_NUM3            =CONVERT(NUMERIC(16,6) ,[EXTRA_INFO_NUM3]),
EXTRA_INFO_NUM4            =CONVERT(NUMERIC(16,6) ,[EXTRA_INFO_NUM4]),
EXTRA_INFO_NUM5            =CONVERT(NUMERIC(16,6) ,[EXTRA_INFO_NUM5]),
RESPONSE_CHANNEL_CODE      =CONVERT(NUMERIC(10)   ,[RESPONSE_CHANNEL_CODE]),
LOAD_DATE                  =CONVERT(DATE         ,[LOAD_DATE]),
PROCESS_TYPE               =CONVERT(NUMERIC(10)   ,[PROCESS_TYPE]),
CALL_YEAR                  =CONVERT(NUMERIC(10)   ,[CALL_YEAR]),
CALL_MONTH                 =CONVERT(NUMERIC(10)   ,[CALL_MONTH]),
SALES_DATE                 =CONVERT(DATE         ,[SALES_DATE]),
VALIDATED_DATE             =CONVERT(DATE         ,[VALIDATED_DATE]),
HAD_UPDATED                =CONVERT(numeric(10)   ,[HAD_UPDATED]),
INSERT_DATE_TIME           =CONVERT(DATE         ,[INSERT_DATE_TIME]),
'AD' as INSURER_CODE,
CONVERT(DATE,GETDATE(),112) as EXTRACT_DATE

FROM [dbo].[Region] 
GO


select * from dbo.viewAniversariante


select CONVERT(DATE,GETDATE(),112)