USE DDS_EPOS_DEV 
GO 
CREATE VIEW V_ACCF_CF_F4_CDR 
AS
SELECT 
CDR_ID                     =[CDR_ID],
FILE_POSESSION_CODE        =[FILE_POSESSION_CODE],
CUSTOMER_ID                =[CUSTOMER_ID],
CAMPAIGN_CODE              =[CAMPAIGN_CODE],
JOB_NAME                   =[JOB_NAME],
DIAL_SEQUENCE              =[DIAL_SEQUENCE],
APPROACH_CODE              =[APPROACH_CODE],
TSR_ID                     =[TSR_ID],
CONTACT_DATE_TIME          =[CONTACT_DATE_TIME],
PLANNED_RECALL_DATETIME    =[PLANNED_RECALL_DATETIME],
LOGGED_HOURS               =[LOGGED_HOURS],
TALK_HOURS                 =[TALK_HOURS],
WRAP_HOURS                 =[WRAP_HOURS],
WAIT_HOURS                 =[WAIT_HOURS],
TM_RESULT_CODE             =[TM_RESULT_CODE],
TSR_RESULT_CODE            =[TSR_RESULT_CODE],
PRODUCT_TYPE_CODE          =[PRODUCT_TYPE_CODE],
SALES_VALIDATION_CODE      =[SALES_VALIDATION_CODE],
SALES_PROD_PLAN_CODE       =[SALES_PROD_PLAN_CODE],
SALES_OPTION_CODE          =[SALES_OPTION_CODE],
SALES_OPT_FAMILY_RELATION  =[SALES_OPT_FAMILY_RELATION],
MONTHLY_PREMIUM            =[MONTHLY_PREMIUM],
INSURED_ID                 =[INSURED_ID],
INSURED_DOB                =[INSURED_DOB],
INSURED_GENDER             =[INSURED_GENDER],
INSURED_OCCUPATION         =[INSURED_OCCUPATION],
SPOUSE_DOB                 =[SPOUSE_DOB],
SPOUSE_GENDER              =[SPOUSE_GENDER],
SUPPORTER_AGE              =[SUPPORTER_AGE],
SUPPORTER_GENDER           =[SUPPORTER_GENDER],
DM_OPT_OUT_DATE            =[DM_OPT_OUT_DATE],
OBTM_OPT_OUT_DATE          =[OBTM_OPT_OUT_DATE],
MOBILE_NUMERIC             =[MOBILE_NUMBER],
PERSONAL_EMAIL_ADDRESS     =[PERSONAL_EMAIL_ADDRESS],
EXTRA_INFO_TEXT_1          =[EXTRA_INFO_TEXT_1],
EXTRA_INFO_TEXT_2          =[EXTRA_INFO_TEXT_2],
EXTRA_INFO_TEXT_3          =[EXTRA_INFO_TEXT_3],
EXTRA_INFO_TEXT_4          =[EXTRA_INFO_TEXT_4],
EXTRA_INFO_TEXT_5          =[EXTRA_INFO_TEXT_5],
EXTRA_INFO_DATE1           =[EXTRA_INFO_DATE1],
EXTRA_INFO_DATE2           =[EXTRA_INFO_DATE2],
EXTRA_INFO_DATE3           =[EXTRA_INFO_DATE3],
EXTRA_INFO_DATE4           =[EXTRA_INFO_DATE4],
EXTRA_INFO_DATE5           =[EXTRA_INFO_DATE5],
EXTRA_INFO_NUM1            =[EXTRA_INFO_NUM1],
EXTRA_INFO_NUM2            =[EXTRA_INFO_NUM2],
EXTRA_INFO_NUM3            =[EXTRA_INFO_NUM3],
EXTRA_INFO_NUM4            =[EXTRA_INFO_NUM4],
EXTRA_INFO_NUM5            =[EXTRA_INFO_NUM5],
RESPONSE_CHANNEL_CODE      =[RESPONSE_CHANNEL_CODE],
LOAD_DATE                  =[LOAD_DATE],
PROCESS_TYPE               =[PROCESS_TYPE],
CALL_YEAR                  =[CALL_YEAR],
CALL_MONTH                 =[CALL_MONTH],
SALES_DATE                 =[SALES_DATE],
VALIDATED_DATE             =[VALIDATED_DATE],
HAD_UPDATED                =[HAD_UPDATED],
INSERT_DATE_TIME           =[INSERT_DATE_TIME],
'AD' as INSURER_CODE,
CONVERT(DATE,GETDATE(),120) as EXTRACT_DATE
FROM dbo.DDS_CDR
WHERE LOAD_DATE > ( 
						SELECT COALESCE(max(LAST_EXTRACT_DATE), CONVERT(DATE,'0001-01-01',120))
						FROM ECCF_ACF_EXTRACT_REF
						WHERE FILE_TYPE = 'CDR'
			      )
					 
GO


select *
from V_ACCF_CF_F4_CDR

insert into ECCF_ACF_EXTRACT_REF
values('CDR',convert(date,'2015-06-30'),getdate())

update ECCF_ACF_EXTRACT_REF
set LAST_EXTRACT_DATE=convert(date,'2015-06-30')

delete from ECCF_ACF_EXTRACT_REF

select count(*) 
from dbo.DDS_CDR

select count(*)
FROM dbo.DDS_CDR
WHERE LOAD_DATE >convert(date,'0001-01-01')

