-- HABILITA PARA O SQL SERVER TRAZER AS INFORMACOES DE PERFORMANCE
 SET STATISTICS io OFF
SET STATISTICS time OFF
GO

--NECESSARIO HABILITAR NO SQL SERVER AS ESTATISTICAS DE CONSULTA DINAMICA QUE FICAM NO TOP MENU.


SELECT FirstName, LastName
  FROM Person.Person_Teste 
       where FirstName like '%Jo%' and LastName = 'Brown';
GO